# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/s3rius/dwm-autoconfig
    rev: master
    hooks:
    -   id: sort_deps
